apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - prometheus/prometheus-config.yaml
  - prometheus/prometheus-statefulset.yaml
  - alertmanager/alertmanager-config.yaml
  - alertmanager/alertmanager-statefulset.yaml
  - thanos/query-deployment.yaml
