apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstore-config
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: "<bucket-name>"
      endpoint: "<s3-endpoint>:443"
      access_key: "<access-key>"
      secret_key: "<secret-key>"
      insecure: false
      signature_version2: false
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 2m
      trace:
        enable: false
